[project]
name = "fishy"
version = "0.1.0"
description = "Lightweight python library for manipulating Fisher matrices"
readme = "README.md"
authors = [
    { name = "binado", email = "bernardopveronese@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "numpy",
    "xarray",
]

[build-system]
requires = ["uv_build>=0.9.18,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.1.0",
    "matplotlib>=3.10.8",
    "pytest>=9.0.2",
]
